name=DevLab_Interface
version=1.1.0
author=UNIT Electronics
maintainer=Jonathan Mejorado Lopez 
sentence=Arduino library interface for DevLab Sensors and external sensors, through I2C, SPI and other communication protocols.
paragraph=
category=Communication
url=https://github.com/UNIT-Electronics-MX/unit_devlab_interface_library
architectures=*
includes=DevLab_Interface.h, DevLab_BusIO.h,DevLab_I2C_Interface.h

